application: chsorganiser
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /(css|images|js|fonts)/(.*)
  static_files: static/\1/\2
  upload: static/(css|images|js|fonts)/(.*)

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.2"
